sudo: required
language: ruby
addons:
    apt:
        packages:
            - aspell
            - aspell-en
services:
  - docker
before_install:
  - docker pull bitcraze/web-builder
script:
  - docker run --rm -v ${PWD}:/module bitcraze/web-builder ./tools/build/build
  - tools/spellcheck/check-spelling.sh
